package pl.groundprotection.fields;

public enum FieldFlag {

    PROTECT_BLOCKS,
    PROTECT_DOORS,
    PROTECT_CHESTS,
    PROTECT_OTHER_BLOCKS,
    PROTECT_ANIMALS,
    PROTECT_HOSTILES,
    PROTECT_OTHER_ENTITIES,
    PREVENT_PVP,
    PREVENT_POTIONS,
    PREVENT_FISHING_ROD,
    PREVENT_BOW,
    PREVENT_SPREAD

}